name: Deploy
on:
  pull_request:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            java_version: [11]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Delete npm package
      uses: actions/delete-package-versions@v5
      with: 
        package-name: vzh-cms
        package-type: npm
    - name: Delete maven package
      uses: actions/delete-package-versions@v5
      with: 
        package-name: vzhyhunou.vzh-cms
        package-type: maven
    - name: Build with Maven
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}